name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Verify Next.js Version
      run: npx next --version

    - name: Build the Application
      run: |
        echo "Disabling ESLint and increasing memory limit for build"
        NODE_OPTIONS=--max_old_space_size=4096 NEXT_DISABLE_ESLINT=1 npm run build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.FRONTEND_PATH }}
          git pull origin main
          npm install --legacy-peer-deps
          NODE_OPTIONS=--max_old_space_size=4096 NEXT_DISABLE_ESLINT=1 npm run build
          # Optional: Restart Nginx or PM2 here if needed
