name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    - name: Build Next.js App
      run: npm run build

    - name: Archive Production Files
      run: |
        mkdir prod
        cp -r .next public package.json prod/

    - name: Copy Files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "prod/*"
        target: "${{ secrets.FRONTEND_PATH }}"

    - name: Run Deploy Script on EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd ${{ secrets.FRONTEND_PATH }}
          npm install --legacy-peer-deps
          pm2 restart my-app || npm run start
